# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "docker"
    directory: "all/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "16/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "15/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "14/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "13/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "12-alpine-3.15/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "12/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "11-alpine-3.14/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "11/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "10/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "9/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "8/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "7/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "6/"
    schedule:
      interval: "weekly"
