name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile*'
      - 'docker-bake.hcl'
      - '**.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile*'
      - 'docker-bake.hcl'
      - '**.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.8.0

      - name: Check formatting
        run: make install-deps && make lint

      - name: Login container registries
        run: |
          echo $CR_PAT | docker login ghcr.io -u shenxianpeng --password-stdin
          docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: Check buildx bake
        run: docker buildx bake --file docker-bake.hcl --print

      - name: Build all images
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: docker buildx bake --file docker-bake.hcl --load

      - name: Publish all images
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        run: docker buildx bake --file docker-bake.hcl --push
