name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile*'
      - 'docker-bake.hcl'
      - '.github/workflows/CI.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile*'
      - 'docker-bake.hcl'
      - '.github/workflows/CI.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag need to publish'
        default: ''
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0

      - name: Check formatting
        run: make install-deps && make lint

      - name: Login container registries
        run: |
          echo $CR_PAT | docker login ghcr.io -u shenxianpeng --password-stdin
          docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: Check buildx bake
        run: docker buildx bake --file docker-bake.hcl --print

      - name: Build all images
        if: github.ref == 'refs/heads/master' && github.event.inputs.tag == ''
        run: docker buildx bake --file docker-bake.hcl --load

      - name: Publish an image for tag ${{ inputs.tag }}
        if: github.ref == 'refs/heads/master' && github.event.inputs.tag != ''
        run: docker buildx bake --file docker-bake.hcl ${{ inputs.tag }} --load

      - name: Publish all images
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch' && github.event.inputs.tag == ''
        run: docker buildx bake --file docker-bake.hcl --push

      - name: Publish an image for tag ${{ inputs.tag }}
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
        run: docker buildx bake --file docker-bake.hcl ${{ inputs.tag }} --push
