name: Publish image

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download image
        run: |
          docker pull xianpengshen/clang-tools:all
          docker tag xianpengshen/clang-tools:all ghcr.io/cpp-linter/clang-tools:all
      - name: Login container registry
        run: |
          echo $CR_PAT | docker login ghcr.io -u shenxianpeng --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - name: Push image to container registry
        run: docker push ghcr.io/cpp-linter/clang-tools:all
