name: Publish images to ghcr.io

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to publish'
        default: 'all 16 15 14 13 12 11 10 9 8'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login container registry
        run: |
          echo $CR_PAT | docker login ghcr.io -u shenxianpeng --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - name: Download and push image to ghcr.io
        run: |
          for tag in ${{ inputs.tag }}; do
            docker pull xianpengshen/clang-tools:$tag
            docker tag xianpengshen/clang-tools:$tag ghcr.io/cpp-linter/clang-tools:$tag
            docker push ghcr.io/cpp-linter/clang-tools:$tag
          done
