name: Push to ghcr.io

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: download image
        run: |
          docker pull xianpengshen/clang-tools:all
          docker tag xianpengshen/clang-tools:all ghcr.io/cpp-linter/clang-tools:all
      - name: push image to GitHub Container registry
        run: docker push ghcr.io/cpp-linter/clang-tools:all
