name: Release Drafter

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  draft-release:
    uses: cpp-linter/.github/.github/workflows/release-drafter.yml@main
    with:
      commitish: master
