name: Release Drafter

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Draft your next Release notes as Pull Requests are merged into the default branch
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
